// auto-generated by sqlc - do not edit
using System;

namespace MySqlConnectorDapperExampleGen;
public class Author
{
    public required long Id { get; init; }
    public required string Name { get; init; }
    public string? Bio { get; init; }
};
public class Book
{
    public required long Id { get; init; }
    public required string Name { get; init; }
    public required long AuthorId { get; init; }
    public string? Description { get; init; }
};
public class MysqlType
{
    public bool? CBool { get; init; }
    public bool? CBoolean { get; init; }
    public short? CTinyint { get; init; }
    public short? CSmallint { get; init; }
    public int? CMediumint { get; init; }
    public int? CInt { get; init; }
    public int? CInteger { get; init; }
    public long? CBigint { get; init; }
    public double? CFloat { get; init; }
    public string? CDecimal { get; init; }
    public string? CDec { get; init; }
    public string? CNumeric { get; init; }
    public string? CFixed { get; init; }
    public double? CDouble { get; init; }
    public double? CDoublePrecision { get; init; }
    public short? CYear { get; init; }
    public DateTime? CDate { get; init; }
    public string? CTime { get; init; }
    public DateTime? CDatetime { get; init; }
    public DateTime? CTimestamp { get; init; }
    public string? CChar { get; init; }
    public string? CNchar { get; init; }
    public string? CNationalChar { get; init; }
    public string? CVarchar { get; init; }
    public string? CTinytext { get; init; }
    public string? CMediumtext { get; init; }
    public string? CText { get; init; }
    public string? CLongtext { get; init; }
    public byte? CBit { get; init; }
    public byte[]? CBinary { get; init; }
    public byte[]? CVarbinary { get; init; }
    public byte[]? CTinyblob { get; init; }
    public byte[]? CBlob { get; init; }
    public byte[]? CMediumblob { get; init; }
    public byte[]? CLongblob { get; init; }
};