repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.4.1
  hooks:
    - id: sqlfluff-fix
      args: [--FIX-EVEN-UNPARSABLE]
- repo: local
  hooks:
    - id: dotnet-format
      name: dotnet format
      entry: dotnet format sqlc-gen-csharp.sln --include
      language: system
      pass_filenames: true
      files: ^((?!GeneratedProtobuf/|examples/).)*\.cs$