# auto-generated by ./scripts/generate_dockerfile.sh - do not edit
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app
COPY *.sln .

COPY CodeGenerator/*.csproj ./CodeGenerator/
COPY Drivers/*.csproj ./Drivers/
COPY EndToEndTests/*.csproj ./EndToEndTests/
COPY Extensions/*.csproj ./Extensions/
COPY GeneratedProtobuf/*.csproj ./GeneratedProtobuf/
COPY LocalRunner/*.csproj ./LocalRunner/
COPY MySqlConnectorDapperExample/*.csproj ./MySqlConnectorDapperExample/
COPY MySqlConnectorExample/*.csproj ./MySqlConnectorExample/
COPY NpgsqlDapperExample/*.csproj ./NpgsqlDapperExample/
COPY NpgsqlExample/*.csproj ./NpgsqlExample/
COPY PluginOptions/*.csproj ./PluginOptions/
COPY SqlcGenCsharp/*.csproj ./SqlcGenCsharp/
COPY SqliteDapperExample/*.csproj ./SqliteDapperExample/
COPY SqliteExample/*.csproj ./SqliteExample/
COPY WasmRunner/*.csproj ./WasmRunner/

COPY CodeGenerator/ ./CodeGenerator/
COPY Drivers/ ./Drivers/
COPY EndToEndTests/ ./EndToEndTests/
COPY Extensions/ ./Extensions/
COPY GeneratedProtobuf/ ./GeneratedProtobuf/
COPY LocalRunner/ ./LocalRunner/
COPY MySqlConnectorDapperExample/ ./MySqlConnectorDapperExample/
COPY MySqlConnectorExample/ ./MySqlConnectorExample/
COPY NpgsqlDapperExample/ ./NpgsqlDapperExample/
COPY NpgsqlExample/ ./NpgsqlExample/
COPY PluginOptions/ ./PluginOptions/
COPY SqlcGenCsharp/ ./SqlcGenCsharp/
COPY SqliteDapperExample/ ./SqliteDapperExample/
COPY SqliteExample/ ./SqliteExample/
COPY WasmRunner/ ./WasmRunner/

RUN dotnet restore

RUN apt-get update && apt-get install -y sqlite3
COPY examples/authors/sqlite/schema.sql sqlite_schema.sql
RUN sqlite3 plugin.db < sqlite_schema.sql
