# auto-generated by ./scripts/generate_dockerfile.sh - do not edit
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app
COPY *.sln .

COPY CodeGenerator/*.csproj ./CodeGenerator/
COPY DebugHelper/*.csproj ./DebugHelper/
COPY Drivers/*.csproj ./Drivers/
COPY Extensions/*.csproj ./Extensions/
COPY GeneratedProtobuf/*.csproj ./GeneratedProtobuf/
COPY MySqlConnectorExample/*.csproj ./MySqlConnectorExample/
COPY NpgsqlExample/*.csproj ./NpgsqlExample/
COPY PluginOptions/*.csproj ./PluginOptions/
COPY SqlcGenCsharp/*.csproj ./SqlcGenCsharp/
COPY SqlcGenCsharpProcess/*.csproj ./SqlcGenCsharpProcess/
COPY SqlcGenCsharpTests/*.csproj ./SqlcGenCsharpTests/
COPY SqlcGenCsharpWasm/*.csproj ./SqlcGenCsharpWasm/

COPY CodeGenerator/ ./CodeGenerator/
COPY DebugHelper/ ./DebugHelper/
COPY Drivers/ ./Drivers/
COPY Extensions/ ./Extensions/
COPY GeneratedProtobuf/ ./GeneratedProtobuf/
COPY MySqlConnectorExample/ ./MySqlConnectorExample/
COPY NpgsqlExample/ ./NpgsqlExample/
COPY PluginOptions/ ./PluginOptions/
COPY SqlcGenCsharp/ ./SqlcGenCsharp/
COPY SqlcGenCsharpProcess/ ./SqlcGenCsharpProcess/
COPY SqlcGenCsharpTests/ ./SqlcGenCsharpTests/
COPY SqlcGenCsharpWasm/ ./SqlcGenCsharpWasm/

RUN dotnet restore
