// auto-generated by sqlc - do not edit
using System.Linq;

namespace SqliteExampleGen;
public readonly record struct TypesSqlite(int? CInteger, decimal? CReal, string? CText, byte[]? CBlob);
public readonly record struct Author(int Id, string Name, string? Bio);
public readonly record struct Book(int Id, string Name, int AuthorId, string? Description);