// auto-generated by sqlc - do not edit
using System;

namespace SqliteDapperExampleGen;
public class Author
{
    public int Id { get; init; }
    public required string Name { get; init; }
    public string? Bio { get; init; }
};
public class Book
{
    public int Id { get; init; }
    public required string Name { get; init; }
    public int AuthorId { get; init; }
    public string? Description { get; init; }
};