// auto-generated by sqlc - do not edit
namespace SqliteDapperExampleGen
{
    using NodaTime;
    using NodaTime.Extensions;
    using NodaTime.Text;
    using System.Linq;

    public class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
    };
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public string Description { get; set; }
    };
    public class TypesSqlite
    {
        public int? CInteger { get; set; }
        public decimal? CReal { get; set; }
        public string CText { get; set; }
        public byte[] CBlob { get; set; }
        public string CTextDatetimeOverride { get; set; }
        public int? CIntegerDatetimeOverride { get; set; }
        public string CTextNodaInstantOverride { get; set; }
        public int? CIntegerNodaInstantOverride { get; set; }
        public string CTextBoolOverride { get; set; }
        public int? CIntegerBoolOverride { get; set; }
    };
}