using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Plugin;
using SqlcGenCsharp.Drivers;
using SqlcGenCsharp.Generators;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using File = Plugin.File;

namespace SqlcGenCsharp;

public class CodeGenerator
{
    private static readonly char[] Separator = ['/'];

    private static readonly string[] ResharperDisables =
    [
        "InconsistentNaming",
        "UnusedAutoPropertyAccessor.Global",
        "NotAccessedPositionalProperty.Global"
    ];

    public CodeGenerator(GenerateRequest generateRequest)
    {
        Options = OptionsParser.Parse(generateRequest);
        DbDriver = Options.InstantiateDriver();
        UtilsGen = new UtilsGen();
        DataClassesGen = new DataClassesGen(DbDriver);
    }

    private ValidOptions Options { get; }
    private IDbDriver DbDriver { get; }

    private DataClassesGen DataClassesGen { get; }
    
    private UtilsGen UtilsGen { get; }

    public GenerateResponse Generate(GenerateRequest generateRequest)
    {
        var namespaceName = GenerateNamespace();
        var fileQueries = GetFileQueries();
        var files = fileQueries
            .Select(fq => GenerateFile(namespaceName, fq.Value, fq.Key))
            .Append(UtilsGen.GenerateFile(namespaceName))
            .ToList();
        return new GenerateResponse { Files = { files } };

        string GenerateNamespace()
        {
            var parts = generateRequest.Settings.Codegen.Out
                .Split(Separator, StringSplitOptions.RemoveEmptyEntries);
            return parts.Length > 0 ? parts[0] : "GeneratedNamespace";
        }

        Dictionary<string, Query[]> GetFileQueries()
        {
            return generateRequest.Queries
                .GroupBy(query => 
                    Options.FilePerQuery 
                        ? $"{query.Name}Query" 
                        : QueryFilenameToClassName(query.Filename))
                .ToDictionary(
                    group => group.Key,
                    group => group.ToArray());
        }
        
        string QueryFilenameToClassName(string filenameWithExtension)
        {
            return string.Concat(
                Path.GetFileNameWithoutExtension(filenameWithExtension).FirstCharToUpper(),
                Path.GetExtension(filenameWithExtension)[1..].FirstCharToUpper());
        }
    }

    private File GenerateFile(string namespaceName, IEnumerable<Query> queries, string className)
    {
        var namespaceDeclaration = FileScopedNamespaceDeclaration(IdentifierName(namespaceName));
        var (usingDirectives, classDeclaration) = GenerateClass(queries, className);
        var root = CompilationUnit()
            .AddUsings(usingDirectives)
            .AddMembers(namespaceDeclaration, classDeclaration)
            .NormalizeWhitespace();

        root = AddResharperDisables(root);
        root = root.AddCommentOnTop($"// auto-generated by sqlc at {DateTime.Now:g} - do not edit");

        return new File
        {
            Name = $"{className}.cs",
            Contents = root.ToByteString()
        };
    }

    private static CompilationUnitSyntax AddResharperDisables(CompilationUnitSyntax compilationUnit)
    {
        return ResharperDisables
            .Aggregate(compilationUnit, (current, resharperDisable) =>
                current.AddCommentOnTop($"// ReSharper disable {resharperDisable}"));
    }

    private (UsingDirectiveSyntax[], MemberDeclarationSyntax) GenerateClass(IEnumerable<Query> queries, string className)
    {
        var (usingDirectives, sharedMemberDeclarations) = DbDriver.Preamble();
        var perQueryMembers = queries.SelectMany(GetMembersForSingleQuery).ToArray();
        return (usingDirectives, GetClassDeclaration());

        ClassDeclarationSyntax GetClassDeclaration()
        {
            var classDeclaration = (ClassDeclarationSyntax)ParseMemberDeclaration(
                    $"class {className}(string {Variable.ConnectionString.Name()})" + "{}")!
                .AddModifiers(Token(SyntaxKind.PublicKeyword));

            return classDeclaration
                .AddMembers(sharedMemberDeclarations)
                .AddMembers(perQueryMembers);
        }
    }

    private MemberDeclarationSyntax[] GetMembersForSingleQuery(Query query)
    {
        return new[]
            {
                GetQueryTextConstant(query),
                GetQueryColumnsDataclass(query),
                GetQueryParamsDataclass(query),
                AddMethodDeclaration(query)
            }
            .Where(member => member != null)
            .Cast<MemberDeclarationSyntax>()
            .ToArray();
    }

    private MemberDeclarationSyntax? GetQueryColumnsDataclass(Query query)
    {
        return query.Columns.Count <= 0 
            ? null 
            : DataClassesGen.Generate(query.Name, ClassMember.Row, query.Columns, Options);
    }

    private MemberDeclarationSyntax? GetQueryParamsDataclass(Query query)
    {
        if (query.Params.Count <= 0) return null;
        var columns = query.Params.Select(p => p.Column);
        return DataClassesGen.Generate(query.Name, ClassMember.Args, columns, Options);
    }

    private MemberDeclarationSyntax GetQueryTextConstant(Query query)
    {
        return ParseMemberDeclaration(
                $"private const string {query.Name}{ClassMember.Sql.Name()} = \"{DbDriver.TransformQuery(query)}\";")!
            .AppendNewLine();
    }
    
    private MemberDeclarationSyntax AddMethodDeclaration(Query query)
    {
        var queryTextConstant = GetInterfaceName(ClassMember.Sql);
        var argInterface = GetInterfaceName(ClassMember.Args);
        var returnInterface = GetInterfaceName(ClassMember.Row);

        return query.Cmd switch
        {
            ":exec" => DbDriver.ExecDeclare(query.Name, queryTextConstant, argInterface, query.Params),
            ":one" => DbDriver.OneDeclare(query.Name, queryTextConstant, argInterface, returnInterface,
                query.Params, query.Columns),
            ":many" => DbDriver.ManyDeclare(query.Name, queryTextConstant, argInterface, returnInterface,
                query.Params, query.Columns),
            ":execlastid" => DbDriver.ExecLastIdDeclare(query.Name, queryTextConstant, argInterface, returnInterface,
                query.Params, query.Columns),
            _ => throw new InvalidDataException()
        };

        string GetInterfaceName(ClassMember classMemberType)
        {
            return $"{query.Name}{classMemberType.Name()}";
        }
    }
}