using Google.Protobuf;
using System;
using File = Plugin.File;


namespace SqlcGenCsharp.Generators;

internal class CsprojGen(string outputDirectory, string projectName, string namespaceName, Options options)
{
    // TODO this logic needs to be moved to the Drivers project
    private const string DefaultDapperVersion = "2.1.66";
    private const string DefaultNpgsqlVersion = "8.0.6";
    private const string DefaultMysqlConnectorVersion = "2.4.0";
    private const string DefaultSqliteVersion = "9.0.0";
    private const string DefaultCsvHelperVersion = "33.0.1";
    private const string DefaultSystemTextJsonVersion = "9.0.6";

    public File GenerateFile()
    {
        var csprojContents = GetFileContents();
        return new File
        {
            Name = $"{projectName}.csproj",
            Contents = ByteString.CopyFromUtf8(csprojContents)
        };
    }

    private string GetFileContents()
    {
        var optionalNullableProperty = options.DotnetFramework.IsDotnetCore() ? Environment.NewLine + "        <Nullable>enable</Nullable>" : "";
        return $"""
                <!--{Consts.AutoGeneratedComment}-->
                <!--Run the following to add the project to the solution:
                   dotnet sln add {outputDirectory}/{projectName}.csproj
                  -->
                <Project Sdk="Microsoft.NET.Sdk">
                
                    <PropertyGroup>
                        <TargetFramework>{options.DotnetFramework.ToName()}</TargetFramework>
                        <RootNamespace>{namespaceName}</RootNamespace>
                        <OutputType>Library</OutputType>{optionalNullableProperty}
                    </PropertyGroup>
                
                {GetPackageReferences()}

                </Project>
                """;

        string GetPackageReferences()
        {
            var optionalDapperPackageReference = options.UseDapper
                ? Environment.NewLine + $"""        <PackageReference Include="Dapper" Version="{GetDapperVersion(options)}"/>"""
                : string.Empty;
            var optionalCsvHelper = options.DriverName is DriverName.MySqlConnector
                ? Environment.NewLine + $"""        <PackageReference Include="CsvHelper" Version="{DefaultCsvHelperVersion}"/>"""
                : string.Empty;
            var optionalSystemTextJson = IsSystemTextJsonNeeded()
                ? Environment.NewLine + $"""        <PackageReference Include="System.Text.Json" Version="{DefaultSystemTextJsonVersion}"/>"""
                : string.Empty;
            return $"""
                <ItemGroup>
                    <PackageReference Include="{options.DriverName.ToName()}" Version="{GetDriverVersion(options)}"/>{optionalDapperPackageReference}{optionalCsvHelper}{optionalSystemTextJson}
                    <PackageReference Include="NodaTime" Version="3.2.0"/>
                </ItemGroup>
            """;
        }
    }

    private bool IsSystemTextJsonNeeded()
    {
        if (options.DotnetFramework.IsDotnetCore())
            return false;
        return options.DriverName is DriverName.MySqlConnector or DriverName.Npgsql;
    }

    private static string GetDriverVersion(Options options)
    {
        if (string.IsNullOrEmpty(options.OverrideDriverVersion))
            return options.DriverName switch
            {
                DriverName.Npgsql => DefaultNpgsqlVersion,
                DriverName.MySqlConnector => DefaultMysqlConnectorVersion,
                DriverName.Sqlite => DefaultSqliteVersion,
                _ => throw new NotSupportedException($"unsupported driver: {options.DriverName}")
            };
        return options.OverrideDriverVersion;
    }

    private static string GetDapperVersion(Options options)
    {
        return string.IsNullOrEmpty(options.OverrideDapperVersion)
            ? DefaultDapperVersion
            : options.OverrideDapperVersion;
    }
}