using Microsoft.CodeAnalysis.CSharp.Syntax;
using Plugin;
using SqlcGenCsharp.Drivers;
using System.Collections.Generic;
using System.Linq;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


namespace SqlcGenCsharp.Generators;

internal class ModelsGen(DbDriver dbDriver, Options options, string namespaceName)
{
    private RootGen RootGen { get; } = new(options);

    private DataClassesGen DataClassesGen { get; } = new(dbDriver);

    public File GenerateFile(Dictionary<string, Table> tables)
    {
        var models = GenerateModelsDataClasses(tables);
        var root = RootGen.CompilationRootGen(IdentifierName(namespaceName),
            [UsingDirective(ParseName("System"))], models);
        root = root.AddCommentOnTop(Consts.AutoGeneratedComment);

        return new File
        {
            Name = "Models.cs",
            Contents = root.ToByteString()
        };
    }

    private MemberDeclarationSyntax[] GenerateModelsDataClasses(Dictionary<string, Table> tables)
    {
        return (
            from table in tables.Values
            let className = $"{table.Rel.Schema}_{table.Rel.Name}"
            select DataClassesGen.Generate(className.ToModelName(), ClassMember.Model, table.Columns, options)
        ).ToArray();
    }
}