// auto-generated by sqlc - do not edit
using NodaTime;
using NodaTime.Extensions;
using NodaTime.Text;
using System.Linq;

namespace SqliteDapperLegacyExampleGen;
public class Author
{
    public required int Id { get; init; }
    public required string Name { get; init; }
    public string? Bio { get; init; }
};
public class Book
{
    public required int Id { get; init; }
    public required string Name { get; init; }
    public required int AuthorId { get; init; }
    public string? Description { get; init; }
};
public class TypesSqlite
{
    public int? CInteger { get; init; }
    public decimal? CReal { get; init; }
    public string? CText { get; init; }
    public byte[]? CBlob { get; init; }
    public string? CTextDatetimeOverride { get; init; }
    public int? CIntegerDatetimeOverride { get; init; }
    public string? CTextNodaInstantOverride { get; init; }
    public int? CIntegerNodaInstantOverride { get; init; }
    public string? CTextBoolOverride { get; init; }
    public int? CIntegerBoolOverride { get; init; }
};