// auto-generated by sqlc - do not edit
using System;

namespace NpgsqlDapperExampleGen;
public class Author
{
    public required long Id { get; init; }
    public required string Name { get; init; }
    public string? Bio { get; init; }
};
public class Book
{
    public required long Id { get; init; }
    public required string Name { get; init; }
    public required long AuthorId { get; init; }
    public string? Description { get; init; }
};
public class PostgresType
{
    public bool? CBoolean { get; init; }
    public byte[]? CBit { get; init; }
    public short? CSmallint { get; init; }
    public int? CInteger { get; init; }
    public long? CBigint { get; init; }
    public decimal? CDecimal { get; init; }
    public decimal? CNumeric { get; init; }
    public float? CReal { get; init; }
    public double? CDoublePrecision { get; init; }
    public DateTime? CDate { get; init; }
    public string? CTime { get; init; }
    public DateTime? CTimestamp { get; init; }
    public string? CChar { get; init; }
    public string? CVarchar { get; init; }
    public string? CCharacterVarying { get; init; }
    public byte[]? CBytea { get; init; }
    public string? CText { get; init; }
    public object? CJson { get; init; }
    public string[]? CTextArray { get; init; }
    public int[]? CIntegerArray { get; init; }
};