#!/usr/bin/env bash

cat <<EOF > Dockerfile
# auto-generated by $0 - do not edit
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app
COPY *.sln .

EOF

projects=$(dotnet sln list | grep csproj | awk -F'/' '{print $1}')
for project in $projects; do
    echo "COPY $project/*.csproj ./$project/" >> Dockerfile
done
echo "" >> Dockerfile
for project in $projects; do
    echo "COPY $project/ ./$project/" >> Dockerfile
done
echo "" >> Dockerfile
echo "RUN dotnet restore" >> Dockerfile