#!/usr/bin/env bash

filename=$1

cat <<EOF > "$filename"
# auto-generated by $0 - do not edit
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

WORKDIR /app
COPY *.sln .

EOF

projects=$(dotnet sln list | grep csproj | awk -F'/' '{print $1}')
for project in $projects; do
    echo "COPY $project/*.csproj ./$project/" >> "$filename"
done
echo "" >> "$filename"
for project in $projects; do
    echo "COPY $project/ ./$project/" >> "$filename"
done

printf "\nRUN dotnet restore\n" >> "$filename"

cat <<EOF >> "$filename"

RUN apt-get update && apt-get install -y sqlite3
COPY examples/authors/sqlite/schema.sql sqlite_schema.sql
RUN sqlite3 plugin.db < sqlite_schema.sql
EOF