// auto-generated by sqlc - do not edit
// ReSharper disable UseObjectOrCollectionInitializer
// ReSharper disable UseAwaitUsing
// ReSharper disable ConvertToUsingDeclaration
// ReSharper disable NotAccessedPositionalProperty.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MySqlConnector;
using System.Globalization;
using System.IO;
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.TypeConversion;
using System.Text;

namespace MySqlConnectorExampleGen;
public class QuerySql
{
    public QuerySql(string connectionString)
    {
        this.ConnectionString = connectionString;
    }

    private string ConnectionString { get; }

    private const string GetAuthorSql = "SELECT id, name, bio FROM authors WHERE name = @name LIMIT 1";
    public readonly record struct GetAuthorRow(long Id, string Name, string? Bio);
    public readonly record struct GetAuthorArgs(string Name);
    public async Task<GetAuthorRow?> GetAuthor(GetAuthorArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetAuthorSql, connection))
            {
                command.Parameters.AddWithValue("@name", args.Name);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    if (await reader.ReadAsync())
                    {
                        return new GetAuthorRow
                        {
                            Id = reader.GetInt64(0),
                            Name = reader.GetString(1),
                            Bio = reader.IsDBNull(2) ? null : reader.GetString(2)
                        };
                    }
                }
            }
        }

        return null;
    }

    private const string ListAuthorsSql = "SELECT id, name, bio FROM authors ORDER BY name";
    public readonly record struct ListAuthorsRow(long Id, string Name, string? Bio);
    public async Task<List<ListAuthorsRow>> ListAuthors()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(ListAuthorsSql, connection))
            {
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<ListAuthorsRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new ListAuthorsRow { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) });
                    }

                    return result;
                }
            }
        }
    }

    private const string CreateAuthorSql = "INSERT INTO authors (id, name, bio) VALUES (@id, @name, @bio)";
    public readonly record struct CreateAuthorArgs(long Id, string Name, string? Bio);
    public async Task CreateAuthor(CreateAuthorArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(CreateAuthorSql, connection))
            {
                command.Parameters.AddWithValue("@id", args.Id);
                command.Parameters.AddWithValue("@name", args.Name);
                command.Parameters.AddWithValue("@bio", args.Bio ?? (object)DBNull.Value);
                await command.ExecuteScalarAsync();
            }
        }
    }

    private const string CreateAuthorReturnIdSql = "INSERT INTO authors (name, bio) VALUES (@name, @bio)";
    public readonly record struct CreateAuthorReturnIdArgs(string Name, string? Bio);
    public async Task<long> CreateAuthorReturnId(CreateAuthorReturnIdArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(CreateAuthorReturnIdSql, connection))
            {
                command.Parameters.AddWithValue("@name", args.Name);
                command.Parameters.AddWithValue("@bio", args.Bio ?? (object)DBNull.Value);
                await command.ExecuteNonQueryAsync();
                return command.LastInsertedId;
            }
        }
    }

    private const string GetAuthorByIdSql = "SELECT id, name, bio FROM authors WHERE id = @id LIMIT 1";
    public readonly record struct GetAuthorByIdRow(long Id, string Name, string? Bio);
    public readonly record struct GetAuthorByIdArgs(long Id);
    public async Task<GetAuthorByIdRow?> GetAuthorById(GetAuthorByIdArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetAuthorByIdSql, connection))
            {
                command.Parameters.AddWithValue("@id", args.Id);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    if (await reader.ReadAsync())
                    {
                        return new GetAuthorByIdRow
                        {
                            Id = reader.GetInt64(0),
                            Name = reader.GetString(1),
                            Bio = reader.IsDBNull(2) ? null : reader.GetString(2)
                        };
                    }
                }
            }
        }

        return null;
    }

    private const string GetAuthorByNamePatternSql = "SELECT id, name, bio FROM authors WHERE name LIKE COALESCE(@name_pattern, '%')";
    public readonly record struct GetAuthorByNamePatternRow(long Id, string Name, string? Bio);
    public readonly record struct GetAuthorByNamePatternArgs(string? NamePattern);
    public async Task<List<GetAuthorByNamePatternRow>> GetAuthorByNamePattern(GetAuthorByNamePatternArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetAuthorByNamePatternSql, connection))
            {
                command.Parameters.AddWithValue("@name_pattern", args.NamePattern ?? (object)DBNull.Value);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<GetAuthorByNamePatternRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new GetAuthorByNamePatternRow { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) });
                    }

                    return result;
                }
            }
        }
    }

    private const string DeleteAuthorSql = "DELETE FROM authors WHERE name = @name";
    public readonly record struct DeleteAuthorArgs(string Name);
    public async Task DeleteAuthor(DeleteAuthorArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(DeleteAuthorSql, connection))
            {
                command.Parameters.AddWithValue("@name", args.Name);
                await command.ExecuteScalarAsync();
            }
        }
    }

    private const string DeleteAllAuthorsSql = "DELETE FROM authors";
    public async Task DeleteAllAuthors()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(DeleteAllAuthorsSql, connection))
            {
                await command.ExecuteScalarAsync();
            }
        }
    }

    private const string UpdateAuthorsSql = "UPDATE authors SET  bio  =  @bio  WHERE  bio  IS  NOT  NULL  ";  
    public readonly record struct UpdateAuthorsArgs(string? Bio);
    public async Task<long> UpdateAuthors(UpdateAuthorsArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(UpdateAuthorsSql, connection))
            {
                command.Parameters.AddWithValue("@bio", args.Bio ?? (object)DBNull.Value);
                return await command.ExecuteNonQueryAsync();
            }
        }
    }

    private const string GetAuthorsByIdsSql = "SELECT id, name, bio FROM authors WHERE id IN (/*SLICE:ids*/@ids)";
    public readonly record struct GetAuthorsByIdsRow(long Id, string Name, string? Bio);
    public readonly record struct GetAuthorsByIdsArgs(long[] Ids);
    public async Task<List<GetAuthorsByIdsRow>> GetAuthorsByIds(GetAuthorsByIdsArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            var sqlText = GetAuthorsByIdsSql;
            sqlText = Utils.GetTransformedString(sqlText, args.Ids, "Ids", "ids");
            using (var command = new MySqlCommand(sqlText, connection))
            {
                for (int i = 0; i < args.Ids.Length; i++)
                    command.Parameters.AddWithValue($"@IdsArg{i}", args.Ids[i]);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<GetAuthorsByIdsRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new GetAuthorsByIdsRow { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) });
                    }

                    return result;
                }
            }
        }
    }

    private const string GetAuthorsByIdsAndNamesSql = "SELECT id, name, bio FROM authors WHERE id IN (/*SLICE:ids*/@ids) AND name IN (/*SLICE:names*/@names)";
    public readonly record struct GetAuthorsByIdsAndNamesRow(long Id, string Name, string? Bio);
    public readonly record struct GetAuthorsByIdsAndNamesArgs(long[] Ids, string[] Names);
    public async Task<List<GetAuthorsByIdsAndNamesRow>> GetAuthorsByIdsAndNames(GetAuthorsByIdsAndNamesArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            var sqlText = GetAuthorsByIdsAndNamesSql;
            sqlText = Utils.GetTransformedString(sqlText, args.Ids, "Ids", "ids");
            sqlText = Utils.GetTransformedString(sqlText, args.Names, "Names", "names");
            using (var command = new MySqlCommand(sqlText, connection))
            {
                for (int i = 0; i < args.Ids.Length; i++)
                    command.Parameters.AddWithValue($"@IdsArg{i}", args.Ids[i]);
                for (int i = 0; i < args.Names.Length; i++)
                    command.Parameters.AddWithValue($"@NamesArg{i}", args.Names[i]);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<GetAuthorsByIdsAndNamesRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new GetAuthorsByIdsAndNamesRow { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) });
                    }

                    return result;
                }
            }
        }
    }

    private const string CreateBookSql = "INSERT INTO books (name, author_id) VALUES (@name, @author_id)";
    public readonly record struct CreateBookArgs(string Name, long AuthorId);
    public async Task<long> CreateBook(CreateBookArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(CreateBookSql, connection))
            {
                command.Parameters.AddWithValue("@name", args.Name);
                command.Parameters.AddWithValue("@author_id", args.AuthorId);
                await command.ExecuteNonQueryAsync();
                return command.LastInsertedId;
            }
        }
    }

    private const string ListAllAuthorsBooksSql = "SELECT authors.id, authors.name, authors.bio, books.id, books.name, books.author_id, books.description  FROM  authors  JOIN  books  ON  authors . id  =  books . author_id  ORDER  BY  authors . name  ";  
    public readonly record struct ListAllAuthorsBooksRow(Author Author, Book Book);
    public async Task<List<ListAllAuthorsBooksRow>> ListAllAuthorsBooks()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(ListAllAuthorsBooksSql, connection))
            {
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<ListAllAuthorsBooksRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new ListAllAuthorsBooksRow { Author = new Author { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) }, Book = new Book { Id = reader.GetInt64(3), Name = reader.GetString(4), AuthorId = reader.GetInt64(5), Description = reader.IsDBNull(6) ? null : reader.GetString(6) } });
                    }

                    return result;
                }
            }
        }
    }

    private const string GetDuplicateAuthorsSql = "SELECT authors1.id, authors1.name, authors1.bio, authors2.id, authors2.name, authors2.bio FROM  authors  authors1  JOIN  authors  authors2  ON  authors1 . name  =  authors2 . name  WHERE  authors1 . id < authors2 . id  ";  
    public readonly record struct GetDuplicateAuthorsRow(Author Author, Author Author2);
    public async Task<List<GetDuplicateAuthorsRow>> GetDuplicateAuthors()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetDuplicateAuthorsSql, connection))
            {
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<GetDuplicateAuthorsRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new GetDuplicateAuthorsRow { Author = new Author { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2) }, Author2 = new Author { Id = reader.GetInt64(3), Name = reader.GetString(4), Bio = reader.IsDBNull(5) ? null : reader.GetString(5) } });
                    }

                    return result;
                }
            }
        }
    }

    private const string GetAuthorsByBookNameSql = "SELECT authors.id, authors.name, authors.bio, books.id, books.name, books.author_id, books.description FROM  authors  JOIN  books  ON  authors . id  =  books . author_id  WHERE  books . name  =  @name  ";  
    public readonly record struct GetAuthorsByBookNameRow(long Id, string Name, string? Bio, Book Book);
    public readonly record struct GetAuthorsByBookNameArgs(string Name);
    public async Task<List<GetAuthorsByBookNameRow>> GetAuthorsByBookName(GetAuthorsByBookNameArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetAuthorsByBookNameSql, connection))
            {
                command.Parameters.AddWithValue("@name", args.Name);
                using (var reader = await command.ExecuteReaderAsync())
                {
                    var result = new List<GetAuthorsByBookNameRow>();
                    while (await reader.ReadAsync())
                    {
                        result.Add(new GetAuthorsByBookNameRow { Id = reader.GetInt64(0), Name = reader.GetString(1), Bio = reader.IsDBNull(2) ? null : reader.GetString(2), Book = new Book { Id = reader.GetInt64(3), Name = reader.GetString(4), AuthorId = reader.GetInt64(5), Description = reader.IsDBNull(6) ? null : reader.GetString(6) } });
                    }

                    return result;
                }
            }
        }
    }

    private const string InsertMysqlTypesSql = "INSERT INTO mysql_types (c_bit, c_tinyint, c_bool, c_boolean, c_int, c_varchar, c_date, c_timestamp) VALUES (@c_bit, @c_tinyint, @c_bool, @c_boolean, @c_int, @c_varchar, @c_date, @c_timestamp)";
    public readonly record struct InsertMysqlTypesArgs(bool? CBit, bool? CTinyint, bool? CBool, bool? CBoolean, int? CInt, string? CVarchar, DateTime? CDate, DateTime? CTimestamp);
    public async Task InsertMysqlTypes(InsertMysqlTypesArgs args)
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(InsertMysqlTypesSql, connection))
            {
                command.Parameters.AddWithValue("@c_bit", args.CBit ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_tinyint", args.CTinyint ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_bool", args.CBool ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_boolean", args.CBoolean ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_int", args.CInt ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_varchar", args.CVarchar ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_date", args.CDate ?? (object)DBNull.Value);
                command.Parameters.AddWithValue("@c_timestamp", args.CTimestamp ?? (object)DBNull.Value);
                await command.ExecuteScalarAsync();
            }
        }
    }

    public readonly record struct InsertMysqlTypesBatchArgs(bool? CBit, bool? CTinyint, bool? CBool, bool? CBoolean, int? CInt, string? CVarchar, DateTime? CDate, DateTime? CTimestamp);
    public async Task InsertMysqlTypesBatch(List<InsertMysqlTypesBatchArgs> args)
    {
        const string supportedDateTimeFormat = "yyyy-MM-dd H:mm:ss";
        var config = new CsvConfiguration(CultureInfo.CurrentCulture)
        {
            Delimiter = ","
        };
        using (var writer = new StreamWriter("input.csv", false, new UTF8Encoding(false)))
        using (var csvWriter = new CsvWriter(writer, config))
        {
            var options = new TypeConverterOptions
            {
                Formats = new[]
                {
                    supportedDateTimeFormat
                }
            };
            csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime>(options);
            csvWriter.Context.TypeConverterOptionsCache.AddOptions<DateTime?>(options);
            await csvWriter.WriteRecordsAsync(args);
        }

        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            var loader = new MySqlBulkLoader(connection)
            {
                Local = true,
                TableName = "mysql_types",
                FieldTerminator = ",",
                FileName = "input.csv",
                FieldQuotationCharacter = '"',
                NumberOfLinesToSkip = 1
            };
            loader.Columns.AddRange(new List<string> { "c_bit", "c_tinyint", "c_bool", "c_boolean", "c_int", "c_varchar", "c_date", "c_timestamp" });
            await loader.LoadAsync();
            await connection.CloseAsync();
        }
    }

    private const string GetMysqlTypesSql = "SELECT c_bit, c_tinyint, c_bool, c_boolean, c_smallint, c_mediumint, c_int, c_year, c_integer, c_bigint, c_decimal, c_dec, c_numeric, c_fixed, c_float, c_double, c_double_precision, c_date, c_time, c_datetime, c_timestamp, c_char, c_nchar, c_national_char, c_varchar, c_tinytext, c_mediumtext, c_text, c_longtext, c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob, c_json FROM mysql_types LIMIT 1";
    public readonly record struct GetMysqlTypesRow(bool? CBit, bool? CTinyint, bool? CBool, bool? CBoolean, int? CSmallint, int? CMediumint, int? CInt, int? CYear, int? CInteger, long? CBigint, string? CDecimal, string? CDec, string? CNumeric, string? CFixed, double? CFloat, double? CDouble, double? CDoublePrecision, DateTime? CDate, string? CTime, DateTime? CDatetime, DateTime? CTimestamp, string? CChar, string? CNchar, string? CNationalChar, string? CVarchar, string? CTinytext, string? CMediumtext, string? CText, string? CLongtext, byte[]? CBinary, byte[]? CVarbinary, byte[]? CTinyblob, byte[]? CBlob, byte[]? CMediumblob, byte[]? CLongblob, string? CJson);
    public async Task<GetMysqlTypesRow?> GetMysqlTypes()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetMysqlTypesSql, connection))
            {
                using (var reader = await command.ExecuteReaderAsync())
                {
                    if (await reader.ReadAsync())
                    {
                        return new GetMysqlTypesRow
                        {
                            CBit = reader.IsDBNull(0) ? null : reader.GetBoolean(0),
                            CTinyint = reader.IsDBNull(1) ? null : reader.GetBoolean(1),
                            CBool = reader.IsDBNull(2) ? null : reader.GetBoolean(2),
                            CBoolean = reader.IsDBNull(3) ? null : reader.GetBoolean(3),
                            CSmallint = reader.IsDBNull(4) ? null : reader.GetInt32(4),
                            CMediumint = reader.IsDBNull(5) ? null : reader.GetInt32(5),
                            CInt = reader.IsDBNull(6) ? null : reader.GetInt32(6),
                            CYear = reader.IsDBNull(7) ? null : reader.GetInt32(7),
                            CInteger = reader.IsDBNull(8) ? null : reader.GetInt32(8),
                            CBigint = reader.IsDBNull(9) ? null : reader.GetInt64(9),
                            CDecimal = reader.IsDBNull(10) ? null : reader.GetString(10),
                            CDec = reader.IsDBNull(11) ? null : reader.GetString(11),
                            CNumeric = reader.IsDBNull(12) ? null : reader.GetString(12),
                            CFixed = reader.IsDBNull(13) ? null : reader.GetString(13),
                            CFloat = reader.IsDBNull(14) ? null : reader.GetDouble(14),
                            CDouble = reader.IsDBNull(15) ? null : reader.GetDouble(15),
                            CDoublePrecision = reader.IsDBNull(16) ? null : reader.GetDouble(16),
                            CDate = reader.IsDBNull(17) ? null : reader.GetDateTime(17),
                            CTime = reader.IsDBNull(18) ? null : reader.GetString(18),
                            CDatetime = reader.IsDBNull(19) ? null : reader.GetDateTime(19),
                            CTimestamp = reader.IsDBNull(20) ? null : reader.GetDateTime(20),
                            CChar = reader.IsDBNull(21) ? null : reader.GetString(21),
                            CNchar = reader.IsDBNull(22) ? null : reader.GetString(22),
                            CNationalChar = reader.IsDBNull(23) ? null : reader.GetString(23),
                            CVarchar = reader.IsDBNull(24) ? null : reader.GetString(24),
                            CTinytext = reader.IsDBNull(25) ? null : reader.GetString(25),
                            CMediumtext = reader.IsDBNull(26) ? null : reader.GetString(26),
                            CText = reader.IsDBNull(27) ? null : reader.GetString(27),
                            CLongtext = reader.IsDBNull(28) ? null : reader.GetString(28),
                            CBinary = reader.IsDBNull(29) ? null : Utils.GetBytes(reader, 29),
                            CVarbinary = reader.IsDBNull(30) ? null : Utils.GetBytes(reader, 30),
                            CTinyblob = reader.IsDBNull(31) ? null : Utils.GetBytes(reader, 31),
                            CBlob = reader.IsDBNull(32) ? null : Utils.GetBytes(reader, 32),
                            CMediumblob = reader.IsDBNull(33) ? null : Utils.GetBytes(reader, 33),
                            CLongblob = reader.IsDBNull(34) ? null : Utils.GetBytes(reader, 34),
                            CJson = reader.IsDBNull(35) ? null : reader.GetString(35)
                        };
                    }
                }
            }
        }

        return null;
    }

    private const string GetMysqlTypesAggSql = "SELECT COUNT(1) AS cnt , c_bit, c_tinyint, c_bool, c_boolean, c_int, c_varchar, c_date, c_timestamp FROM  mysql_types  GROUP  BY  c_bit , c_tinyint, c_bool, c_boolean, c_int, c_varchar, c_date, c_timestamp LIMIT  1  ";  
    public readonly record struct GetMysqlTypesAggRow(long Cnt, bool? CBit, bool? CTinyint, bool? CBool, bool? CBoolean, int? CInt, string? CVarchar, DateTime? CDate, DateTime? CTimestamp);
    public async Task<GetMysqlTypesAggRow?> GetMysqlTypesAgg()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(GetMysqlTypesAggSql, connection))
            {
                using (var reader = await command.ExecuteReaderAsync())
                {
                    if (await reader.ReadAsync())
                    {
                        return new GetMysqlTypesAggRow
                        {
                            Cnt = reader.GetInt64(0),
                            CBit = reader.IsDBNull(1) ? null : reader.GetBoolean(1),
                            CTinyint = reader.IsDBNull(2) ? null : reader.GetBoolean(2),
                            CBool = reader.IsDBNull(3) ? null : reader.GetBoolean(3),
                            CBoolean = reader.IsDBNull(4) ? null : reader.GetBoolean(4),
                            CInt = reader.IsDBNull(5) ? null : reader.GetInt32(5),
                            CVarchar = reader.IsDBNull(6) ? null : reader.GetString(6),
                            CDate = reader.IsDBNull(7) ? null : reader.GetDateTime(7),
                            CTimestamp = reader.IsDBNull(8) ? null : reader.GetDateTime(8)
                        };
                    }
                }
            }
        }

        return null;
    }

    private const string TruncateMysqlTypesSql = "TRUNCATE TABLE mysql_types";
    public async Task TruncateMysqlTypes()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            using (var command = new MySqlCommand(TruncateMysqlTypesSql, connection))
            {
                await command.ExecuteScalarAsync();
            }
        }
    }
}