name: CI

on:
  push:
    branches: [ "main", "improve-ci" ]
  pull_request:
    paths:
      - "!**.md"

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        architecture: [ "x64", "arm64" ]
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: install wasm workload
        run: dotnet workload install wasi-experimental
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.25.0'
      - uses: hoverkraft-tech/compose-action@v1.5.1
        with:
         services: |
           mysqldb
           postgresdb
           plugin-tests
      - name: Dotenv Action  
        uses: falti/dotenv-action@v1.1.2
      - name: test dotnet output project
        run: |
          tests_container_id=$(docker ps -aqf "name=plugin-tests")
          echo "${tests_container_id}"
          docker wait "plugin-tests"
        shell: bash
      # - name: Test generated code (.exe)
      #   run: make test-process-plugin-ci
      # - name: Test generated code (.wasm)
      #   run: make test-wasm-plugin
