name: Remove Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  issues: write
  contents: write

jobs:
  remove_stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Stale Branches
        uses: crs-k/stale-branches@v8.2.2
        with:
          days-before-stale: 30
          days-before-delete: 45
          pr-check: true